---
  websocket:
    port: 3000
  keepAliveTime: 55000
  log4js:
    pm2: true
    appenders:
      stdout: # 標準出力
        type: "console"
      stderr: # 標準エラー出力
        type: "stderr"
      ws: # WebSocket通信ログ
        type: "dateFile"
        filename: "/var/log/local/ws-chat-example/ws.log"
        pattern: "-yyyy-MM-dd"
        backups: 10
      error: # エラーログ
        type: "dateFile"
        filename: "/var/log/local/ws-chat-example/error.log"
        pattern: "-yyyy-MM-dd"
        maxLogSize: 107374182400 # 100MB
      debug: # デバッグログ
        type: "file"
        filename: "/var/log/local/ws-chat-example/debug.log"
        backups: 10
        maxLogSize: 10737418240 # 10MB
    categories:
      default:
        appenders:
          - "stdout"
          - "debug"
        level: "debug"
      ws:
        appenders:
          - "stdout"
          - "ws"
        level: "info"
      error:
        appenders:
          - "stderr"
          - "error"
        level: "debug"