---
  log4js:
    pm2: false
    appenders:
      stdout: # 標準出力
        type: "console"
      stderr: # 標準エラー出力
        type: "stderr"
    categories:
      default:
        appenders:
          - "stdout"
        level: "info"
      ws:
        appenders:
          - "stdout"
        level: "info"
      error:
        appenders:
          - "stderr"
        level: "debug"
