---
  log4js:
    appenders:
      - type: "console"
        category: "ws" # WebSocketログ
      - type: "console"
        category: "http" # 通信ログ
      - type: "console"
        category: "error" # エラーログ
      - type: "console"
        category: "debug" # デバッグログ
      - type: "console" # コンソール
    levels:
      ws: "INFO"
      http: "INFO"
      error: "INFO"
      debug: "INFO"
    replaceConsole: false
